const ExcelJS = require('exceljs')
const path = require('path')
const fs = require('fs')

const EXCEL_OUTPUT_DIR = path.join(__dirname, '..', 'uploads', 'excel')

// Ensure output directory exists
if (!fs.existsSync(EXCEL_OUTPUT_DIR)) {
  fs.mkdirSync(EXCEL_OUTPUT_DIR, { recursive: true })
}

/**
 * Generates a formatted .xlsx file from AI-analyzed data
 * @param {Object} analysis - { title, headers, rows, summary }
 * @param {string} uploadId - Used for unique filename
 * @returns {string} absolute path to the generated Excel file
 */
const generateExcel = async (analysis, uploadId) => {
  const workbook = new ExcelJS.Workbook()
  workbook.creator = 'LedgerScan AI'
  workbook.created = new Date()

  const sheetName = (analysis.summary?.documentType || 'Data').slice(0, 30)
  const worksheet = workbook.addWorksheet(sheetName)

  const headers = analysis.headers || ['Column 1']
  const rows = analysis.rows || []

  // ── Title Row ──────────────────────────────────────────
  worksheet.mergeCells(1, 1, 1, headers.length)
  const titleCell = worksheet.getCell('A1')
  titleCell.value = analysis.title || 'LedgerScan Export'
  titleCell.font = { name: 'Calibri', bold: true, size: 14, color: { argb: 'FF1A1F36' } }
  titleCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFE8F0FE' } }
  titleCell.alignment = { horizontal: 'center', vertical: 'middle' }
  worksheet.getRow(1).height = 32

  // ── Summary Row (if available) ──────────────────────────
  let dataStartRow = 3
  if (analysis.summary) {
    worksheet.mergeCells(2, 1, 2, headers.length)
    const summaryCell = worksheet.getCell('A2')
    const summaryParts = []
    if (analysis.summary.date) summaryParts.push(`Date: ${analysis.summary.date}`)
    if (analysis.summary.totalAmount) summaryParts.push(`Total: ${analysis.summary.totalAmount}`)
    if (analysis.summary.itemCount) summaryParts.push(`Items: ${analysis.summary.itemCount}`)
    summaryCell.value = summaryParts.join('   |   ') || 'Generated by LedgerScan'
    summaryCell.font = { name: 'Calibri', size: 10, color: { argb: 'FF6B7280' }, italic: true }
    summaryCell.alignment = { horizontal: 'center' }
    dataStartRow = 4
  }

  // ── Header Row ─────────────────────────────────────────
  const headerRow = worksheet.getRow(dataStartRow)
  headers.forEach((header, i) => {
    const cell = headerRow.getCell(i + 1)
    cell.value = header
    cell.font = { name: 'Calibri', bold: true, size: 11, color: { argb: 'FFFFFFFF' } }
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF4F8EF7' } }
    cell.alignment = { horizontal: 'center', vertical: 'middle' }
    cell.border = {
      top: { style: 'thin', color: { argb: 'FF3B82F6' } },
      bottom: { style: 'thin', color: { argb: 'FF3B82F6' } },
      left: { style: 'thin', color: { argb: 'FF3B82F6' } },
      right: { style: 'thin', color: { argb: 'FF3B82F6' } },
    }
  })
  headerRow.height = 22

  // ── Data Rows ──────────────────────────────────────────
  rows.forEach((rowData, rowIdx) => {
    const row = worksheet.getRow(dataStartRow + 1 + rowIdx)
    const isEven = rowIdx % 2 === 0

    rowData.forEach((cellValue, colIdx) => {
      const cell = row.getCell(colIdx + 1)
      cell.value = cellValue ?? ''
      cell.font = { name: 'Calibri', size: 10 }
      cell.fill = {
        type: 'pattern',
        pattern: 'solid',
        fgColor: { argb: isEven ? 'FFFAFBFF' : 'FFFFFFFF' },
      }
      cell.border = {
        top: { style: 'hair', color: { argb: 'FFE5E9F2' } },
        bottom: { style: 'hair', color: { argb: 'FFE5E9F2' } },
        left: { style: 'hair', color: { argb: 'FFE5E9F2' } },
        right: { style: 'hair', color: { argb: 'FFE5E9F2' } },
      }
      cell.alignment = { vertical: 'middle', wrapText: true }
    })
    row.height = 18
  })

  // ── Auto Column Widths ─────────────────────────────────
  worksheet.columns.forEach((col, i) => {
    let maxLen = (headers[i] || '').toString().length + 4
    rows.forEach(row => {
      const val = (row[i] || '').toString()
      if (val.length > maxLen) maxLen = val.length
    })
    col.width = Math.min(Math.max(maxLen, 10), 50)
  })

  // ── Footer Row ─────────────────────────────────────────
  const footerRowNum = dataStartRow + 1 + rows.length + 1
  worksheet.mergeCells(footerRowNum, 1, footerRowNum, headers.length)
  const footerCell = worksheet.getCell(footerRowNum, 1)
  footerCell.value = `Generated by LedgerScan AI  •  ${new Date().toLocaleDateString('en-IN')}  •  ledgerscan.ai`
  footerCell.font = { name: 'Calibri', size: 9, color: { argb: 'FF9CA3AF' }, italic: true }
  footerCell.alignment = { horizontal: 'center' }

  // ── Save File ──────────────────────────────────────────
  const fileName = `ledgerscan_${uploadId}_${Date.now()}.xlsx`
  const filePath = path.join(EXCEL_OUTPUT_DIR, fileName)
  await workbook.xlsx.writeFile(filePath)

  return filePath
}

/**
 * Updates an existing Excel file by appending new rows
 */
const updateExcel = async (existingFilePath, aiAnalysis) => {
  if (!fs.existsSync(existingFilePath)) {
    throw new Error('Existing Excel file not found')
  }

  const workbook = new ExcelJS.Workbook()
  await workbook.xlsx.readFile(existingFilePath)
  const worksheet = workbook.worksheets[0]

  const newRows = aiAnalysis.rows || []
  if (newRows.length === 0) return existingFilePath

  // Find where data ends (ignoring footer).
  // The footer in generateExcel is separated by an empty row.
  // We can just find the footer row (which contains 'Generated by LedgerScan AI') and remove it.
  let footerRowIdx = -1
  worksheet.eachRow((row, rowNumber) => {
    const cellValue = row.getCell(1).value
    if (typeof cellValue === 'string' && cellValue.includes('Generated by LedgerScan AI')) {
      footerRowIdx = rowNumber
    }
  })

  let startRow = worksheet.rowCount + 1
  if (footerRowIdx !== -1) {
    // Clear footer
    worksheet.spliceRows(footerRowIdx, 1)
    startRow = footerRowIdx
  }

  // Append new rows
  newRows.forEach((rowData, rowIdx) => {
    const row = worksheet.getRow(startRow + rowIdx)
    const isEven = (startRow + rowIdx) % 2 === 0

    rowData.forEach((cellValue, colIdx) => {
      const cell = row.getCell(colIdx + 1)
      cell.value = cellValue ?? ''
      cell.font = { name: 'Calibri', size: 10 }
      cell.fill = {
        type: 'pattern',
        pattern: 'solid',
        fgColor: { argb: isEven ? 'FFFAFBFF' : 'FFFFFFFF' },
      }
      cell.border = {
        top: { style: 'hair', color: { argb: 'FFE5E9F2' } },
        bottom: { style: 'hair', color: { argb: 'FFE5E9F2' } },
        left: { style: 'hair', color: { argb: 'FFE5E9F2' } },
        right: { style: 'hair', color: { argb: 'FFE5E9F2' } },
      }
      cell.alignment = { vertical: 'middle', wrapText: true }
    })
    row.height = 18
  })

  // Add footer back
  const newFooterRowNum = startRow + newRows.length + 1
  const headerCount = worksheet.getRow(3).actualCellCount || newRows[0]?.length || 1 // roughly
  worksheet.mergeCells(newFooterRowNum, 1, newFooterRowNum, Math.max(headerCount, 1))
  const footerCell = worksheet.getCell(newFooterRowNum, 1)
  footerCell.value = `Generated by LedgerScan AI  •  ${new Date().toLocaleDateString('en-IN')}  •  ledgerscan.ai (Updated)`
  footerCell.font = { name: 'Calibri', size: 9, color: { argb: 'FF9CA3AF' }, italic: true }
  footerCell.alignment = { horizontal: 'center' }

  await workbook.xlsx.writeFile(existingFilePath)
  return existingFilePath
}

/**
 * Normalize a header string for comparison: lowercase, trim, remove special chars
 */
const normalizeHeader = (h) => {
  return (h || '').toString().toLowerCase().trim()
    .replace(/[^a-z0-9\s]/g, '')
    .replace(/\s+/g, ' ')
}

/**
 * Smart merge: reads the existing Excel file's headers, maps new data columns
 * to existing columns (by name matching), and appends rows accordingly.
 * If new columns exist that are not in the old file, they are added.
 * If old columns are missing from new data, empty cells are used.
 *
 * @param {string} existingFilePath - Absolute path to the existing .xlsx file
 * @param {Object} aiAnalysis - { headers: [...], rows: [[...], ...], ... }
 * @returns {Object} { filePath, mergeInfo: { oldCols, newCols, addedCols, totalRows } }
 */
const mergeExcel = async (existingFilePath, aiAnalysis) => {
  if (!fs.existsSync(existingFilePath)) {
    throw new Error('Existing Excel file not found')
  }

  const workbook = new ExcelJS.Workbook()
  await workbook.xlsx.readFile(existingFilePath)
  const worksheet = workbook.worksheets[0]

  const newHeaders = aiAnalysis.headers || []
  const newRows = aiAnalysis.rows || []
  if (newRows.length === 0 && newHeaders.length === 0) {
    return { filePath: existingFilePath, mergeInfo: { oldCols: 0, newCols: 0, addedCols: 0, totalRows: 0 } }
  }

  // ── Find existing header row (row with blue background = header row) ──
  let headerRowIdx = -1
  let existingHeaders = []
  worksheet.eachRow((row, rowNumber) => {
    // Check for header row: has blue fill or is row 3 or 4 (typical positions)
    const cell = row.getCell(1)
    const fill = cell.fill
    if (fill && fill.fgColor && (fill.fgColor.argb === 'FF4F8EF7' || fill.fgColor.argb === '4F8EF7')) {
      headerRowIdx = rowNumber
      const headers = []
      row.eachCell((c, colNum) => {
        headers.push({ col: colNum, value: c.value?.toString() || '' })
      })
      existingHeaders = headers
    }
  })

  // Fallback: try row 4 (with summary) or row 3 (no summary)
  if (headerRowIdx === -1) {
    for (const tryRow of [4, 3]) {
      const row = worksheet.getRow(tryRow)
      if (row.getCell(1).value) {
        headerRowIdx = tryRow
        row.eachCell((c, colNum) => {
          existingHeaders.push({ col: colNum, value: c.value?.toString() || '' })
        })
        break
      }
    }
  }

  if (headerRowIdx === -1 || existingHeaders.length === 0) {
    // Cannot determine headers – fall back to simple append
    return { filePath: await updateExcel(existingFilePath, aiAnalysis), mergeInfo: { oldCols: 0, newCols: newHeaders.length, addedCols: 0, totalRows: newRows.length } }
  }

  const oldHeaderNames = existingHeaders.map(h => h.value)
  const normalizedOld = oldHeaderNames.map(normalizeHeader)

  // ── Build column mapping: new header index → old column index ──
  // If a new header matches an old one, map it. Otherwise, it's a new column to add.
  const columnMap = [] // Array of { newIdx, oldColIdx (1-based), headerName }
  const addedHeaders = [] // Headers that don't exist in old file

  newHeaders.forEach((nh, newIdx) => {
    const normalizedNew = normalizeHeader(nh)
    const oldIdx = normalizedOld.findIndex(oh => oh === normalizedNew)
    if (oldIdx !== -1) {
      columnMap.push({ newIdx, oldColIdx: existingHeaders[oldIdx].col, headerName: nh })
    } else {
      // Try partial / fuzzy match (contains)
      const partialIdx = normalizedOld.findIndex(oh =>
        oh.includes(normalizedNew) || normalizedNew.includes(oh)
      )
      if (partialIdx !== -1) {
        columnMap.push({ newIdx, oldColIdx: existingHeaders[partialIdx].col, headerName: nh })
      } else {
        addedHeaders.push({ newIdx, headerName: nh })
      }
    }
  })

  // ── If there are new columns, add them to the header row ──
  let totalCols = existingHeaders.length
  const addedColMap = [] // { newIdx, oldColIdx } for added columns
  addedHeaders.forEach(ah => {
    totalCols += 1
    const colIdx = totalCols
    // Add header cell
    const headerCell = worksheet.getRow(headerRowIdx).getCell(colIdx)
    headerCell.value = ah.headerName
    headerCell.font = { name: 'Calibri', bold: true, size: 11, color: { argb: 'FFFFFFFF' } }
    headerCell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF4F8EF7' } }
    headerCell.alignment = { horizontal: 'center', vertical: 'middle' }
    headerCell.border = {
      top: { style: 'thin', color: { argb: 'FF3B82F6' } },
      bottom: { style: 'thin', color: { argb: 'FF3B82F6' } },
      left: { style: 'thin', color: { argb: 'FF3B82F6' } },
      right: { style: 'thin', color: { argb: 'FF3B82F6' } },
    }
    addedColMap.push({ newIdx: ah.newIdx, oldColIdx: colIdx })
    columnMap.push({ newIdx: ah.newIdx, oldColIdx: colIdx, headerName: ah.headerName })
  })

  // ── Update title row merge if columns were added ──
  if (addedHeaders.length > 0) {
    try {
      // Unmerge row 1 and re-merge with new width
      worksheet.unMergeCells(1, 1, 1, existingHeaders.length)
    } catch {}
    try {
      worksheet.mergeCells(1, 1, 1, totalCols)
    } catch {}
  }

  // ── Find footer row and remove it ──
  let footerRowIdx = -1
  worksheet.eachRow((row, rowNumber) => {
    const cellValue = row.getCell(1).value
    if (typeof cellValue === 'string' && cellValue.includes('Generated by LedgerScan AI')) {
      footerRowIdx = rowNumber
    }
  })

  let startRow = worksheet.rowCount + 1
  if (footerRowIdx !== -1) {
    worksheet.spliceRows(footerRowIdx, 1)
    startRow = footerRowIdx
  }

  // Also remove the empty row before footer if present
  if (startRow > 1) {
    const prevRow = worksheet.getRow(startRow - 1)
    let isEmpty = true
    prevRow.eachCell(c => { if (c.value) isEmpty = false })
    if (isEmpty) {
      startRow = startRow - 1
    }
  }

  // ── Append new rows with column mapping ──
  newRows.forEach((rowData, rowIdx) => {
    const row = worksheet.getRow(startRow + rowIdx)
    const isEven = (startRow + rowIdx) % 2 === 0

    // Fill all columns with empty string first
    for (let c = 1; c <= totalCols; c++) {
      const cell = row.getCell(c)
      if (!cell.value) cell.value = ''
      cell.font = { name: 'Calibri', size: 10 }
      cell.fill = {
        type: 'pattern',
        pattern: 'solid',
        fgColor: { argb: isEven ? 'FFFAFBFF' : 'FFFFFFFF' },
      }
      cell.border = {
        top: { style: 'hair', color: { argb: 'FFE5E9F2' } },
        bottom: { style: 'hair', color: { argb: 'FFE5E9F2' } },
        left: { style: 'hair', color: { argb: 'FFE5E9F2' } },
        right: { style: 'hair', color: { argb: 'FFE5E9F2' } },
      }
      cell.alignment = { vertical: 'middle', wrapText: true }
    }

    // Map new data to correct columns
    columnMap.forEach(({ newIdx, oldColIdx }) => {
      const cell = row.getCell(oldColIdx)
      cell.value = rowData[newIdx] ?? ''
    })

    row.height = 18
  })

  // ── Add footer back ──
  const newFooterRowNum = startRow + newRows.length + 1
  try {
    worksheet.mergeCells(newFooterRowNum, 1, newFooterRowNum, totalCols)
  } catch {}
  const footerCell = worksheet.getCell(newFooterRowNum, 1)
  footerCell.value = `Generated by LedgerScan AI  •  ${new Date().toLocaleDateString('en-IN')}  •  ledgerscan.ai (Merged)`
  footerCell.font = { name: 'Calibri', size: 9, color: { argb: 'FF9CA3AF' }, italic: true }
  footerCell.alignment = { horizontal: 'center' }

  // ── Auto-width for new columns ──
  for (let c = existingHeaders.length + 1; c <= totalCols; c++) {
    const col = worksheet.getColumn(c)
    let maxLen = 10
    col.eachCell(cell => {
      const len = (cell.value || '').toString().length
      if (len > maxLen) maxLen = len
    })
    col.width = Math.min(maxLen + 4, 50)
  }

  await workbook.xlsx.writeFile(existingFilePath)

  // Count total data rows (from header to footer)
  let totalDataRows = 0
  for (let r = headerRowIdx + 1; r < newFooterRowNum; r++) {
    const row = worksheet.getRow(r)
    let hasData = false
    row.eachCell(c => { if (c.value && c.value !== '') hasData = true })
    if (hasData) totalDataRows++
  }

  return {
    filePath: existingFilePath,
    mergeInfo: {
      oldCols: oldHeaderNames.length,
      newCols: newHeaders.length,
      addedCols: addedHeaders.length,
      totalRows: totalDataRows,
      mergedHeaders: [...oldHeaderNames, ...addedHeaders.map(h => h.headerName)],
      newRowsAdded: newRows.length,
    }
  }
}

module.exports = { generateExcel, updateExcel, mergeExcel }
